- ESC + M => Markdown 모드 전환
- ESC + Y => Code 모드 전환
- 현재 셀 실행만 진행 => ctrl + enter
- 현재 셀 실행 후 아래 셀 없으면 셀 추가 후 이동 => shift + Enter
- 패키지 설치: 
    * !pip install 패키지명 / %pip install 패키지명
    * conda 설치 명령어 미지원 => Terminal 실행 후 본인의 가상환경에서 설치해야 함
    * pip 설치만 지원하는 패키지는 pip로 설치
    * 그 외는 conda로 설치하는 것이 패키지 충돌을 예방할 수 있음

In [3]:
import pandas as pd

In [4]:
## ----------------------------------------------------------
##-> 데이터 준비
## ----------------------------------------------------------
jumsu = [[99, 77, 55], 
         [77, 88, 66]]

##-> 행 인덱스
idx = ['0번', '1번']

##-> 열 인덱스
cols = ['국어', '체육', '과학']

In [5]:
## ----------------------------------------------------------
## 함수 기능: DataFrame 객체의 속성 출력 기능
## 함수 이름: print_attr
## 매개변수: df          - 시리즈 인스턴스/객체
##         df_name      - 시리즈 인스턴스/객체 이름
## 반환결과: 없음
## ----------------------------------------------------------
def print_attr(df, df_name):
    print(f'\n---[{df_name} 속성 읽기]---')
    print(f'인덱스: {df.index}')
    print(f'컬럼즈: {df.columns}')
    print(f'데이터:\n{df.values}, \n{type(df.values)}')
    print(f'형  태: {df.shape}')         ## 1차원으로 원소 수 반환
    print(f'차  원: {df.ndim}차원')      ## 1차원
    print(f'타  입:\n{df.dtypes}')       ## 컬럼별 타입
    print(f'데이터프레임:\n{df}')

In [6]:
## ----------------------------------------------------------
##-> DataFrame으로 변환 저장
## ----------------------------------------------------------
##-> 데이터, 행인덱스 지정
dataDF1 = pd.DataFrame(jumsu, idx)

##-> 데이터, 행인덱스, 열인덱스 지정
dataDF2 = pd.DataFrame(jumsu, idx, cols)

##-> 데이터, 행인덱스, 열인덱스, dtype 지정
dataDF3 = pd.DataFrame(jumsu, idx, cols, dtype='int8')


In [7]:
## ----------------------------------------------------------
##-> DataFrame 인스턴스의 속성 읽기
## ----------------------------------------------------------
## -> Data, index
print_attr(dataDF1, 'dataDF1')

##-> Data, index, columns
print_attr(dataDF2, 'dataDF2')

##-> Data, index, columns, dtype
print_attr(dataDF3, 'dataDF3')


---[dataDF1 속성 읽기]---
인덱스: Index(['0번', '1번'], dtype='object')
컬럼즈: RangeIndex(start=0, stop=3, step=1)
데이터:
[[99 77 55]
 [77 88 66]], 
<class 'numpy.ndarray'>
형  태: (2, 3)
차  원: 2차원
타  입:
0    int64
1    int64
2    int64
dtype: object
데이터프레임:
     0   1   2
0번  99  77  55
1번  77  88  66

---[dataDF2 속성 읽기]---
인덱스: Index(['0번', '1번'], dtype='object')
컬럼즈: Index(['국어', '체육', '과학'], dtype='object')
데이터:
[[99 77 55]
 [77 88 66]], 
<class 'numpy.ndarray'>
형  태: (2, 3)
차  원: 2차원
타  입:
국어    int64
체육    int64
과학    int64
dtype: object
데이터프레임:
    국어  체육  과학
0번  99  77  55
1번  77  88  66

---[dataDF3 속성 읽기]---
인덱스: Index(['0번', '1번'], dtype='object')
컬럼즈: Index(['국어', '체육', '과학'], dtype='object')
데이터:
[[99 77 55]
 [77 88 66]], 
<class 'numpy.ndarray'>
형  태: (2, 3)
차  원: 2차원
타  입:
국어    int8
체육    int8
과학    int8
dtype: object
데이터프레임:
    국어  체육  과학
0번  99  77  55
1번  77  88  66
